version: '3.8'

services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
#    container_name: elasticsearch
#    environment:
#      - node.name=elasticsearch
#      - cluster.name=es-docker-cluster
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - xpack.security.enabled=false
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    volumes:
#      - es_data:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#    networks:
#      - elastic
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.11.1
#    container_name: kibana
#    ports:
#      - "5601:5601"
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    depends_on:
#      - elasticsearch
#    networks:
#      - elastic

  # --- The MASTER Database (for Writes) ---
  db-master:
    image: postgres:15
    container_name: postgres-master
    volumes:
      - ./data/master:/var/lib/postgresql/data
      - ./conf/master/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./conf/master/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./init-scripts/create_replication_user.sql:/docker-entrypoint-initdb.d/create_replication_user.sql

    ports:
      - "5432:5432" # Master is on the default port
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # --- Special user for replication ---
#      - POSTGRES_REPLICATION_USER=replicator
#      - POSTGRES_REPLICATION_PASSWORD=replicator_password

    # FIX 1: Explicitly tell Postgres to use the mounted config files
    command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d mydatabase" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- The SLAVE Database (for Reads) ---
#  db-slave:
#    image: postgres:15
#    container_name: postgres-slave
#    ports:
#      - "5433:5432" # Slave is on port 5433 to avoid conflict
#    volumes:
#      - ./data/slave:/var/lib/postgresql/data
#    environment:
#      # These are needed for the container to start, but it will be overwritten by the backup
#      - POSTGRES_DB=mydatabase
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - PGDATA=/var/lib/postgresql/data # Explicitly define data directory
#    command: >
#      bash -c "
#        # 1. Wait for the master to be ready
#        until pg_isready -h db-master -p 5432; do
#          echo 'Waiting for master database...'
#          sleep 2;
#        done;
#
#        # 2. Clean out the existing data directory
#        rm -rf /var/lib/postgresql/data/*
#
#        # 3. Create a base backup from the master
#        echo 'Creating base backup from master...'
#        PGPASSWORD=replicator_password pg_basebackup -h db-master -p 5432 -U replicator -D /var/lib/postgresql/data -Fp -Xs -R;
#
#        # FIX 2: changing permission from user to postgres
#         chown -R postgres:postgres /var/lib/postgresql/data
#         chmod 700 /var/lib/postgresql/data
#
#        # 4. Start the PostgreSQL server in standby mode
#        echo 'Starting slave server...'
#
#        # Start the PostgreSQL server AS THE 'postgres' USER
#        exec gosu postgres postgres
#      "
#    depends_on:
#      db-master:
#        condition: service_healthy # Wait for the master's healthcheck to pass

#  networks:
#    default:
#      driver: bridge

volumes:
  es_data:
    driver: local

networks:
  elastic:
    driver: bridge
