# TYPE  DATABASE        USER            ADDRESS                 METHOD
# Allow all local connections for healthchecks and other internal processes
local   all             all                                     trust

# Allow the 'replicator' user to connect for replication from any IP
host    replication     replicator      0.0.0.0/0               md5

# Allow all other users to connect normally
host    all             all             0.0.0.0/0               md5
