spring:
  application:
    name: simple_admin_v2
  datasource:
    master:
      url: jdbc:postgresql://localhost:5432/mydatabase
      username: postgres
      password: postgres
    slave:
      url: jdbc:postgresql://localhost:5433/mydatabase
      username: postgres
      password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: never
      data-locations: classpath:data.sql,classpath:dummy_device_data.sql,classpath:policy_data.sql

logging:
  level:
    root: INFO
    com.tikam.simple_admin_v2: DEBUG
    org.hibernate.SQL: DEBUG
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

device:
  stats:
    limit: 500
    responseSize: 100

#  networks:
#    default:
#      driver: bridge

volumes:
  es_data:
    driver: local

networks:
  elastic:
    driver: bridge